# Use the official Python image as the base image
FROM public.ecr.aws/lambda/python:3.12

# Set the working directory in the container
WORKDIR /var/task

COPY requirements.txt .
COPY endpoints/get_card.py .
COPY endpoints/models.py .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["get_card.lambda_handler"]
